[package]
name = "aqua-dht"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "aqua-dht"
path = "src/main.rs"

[dependencies]
fluence = "0.6.2"
fce-sqlite-connector = "0.4.0"
fstrings = "0.2.3"

[dev-dependencies]
fluence-test = {branch = "fixup_branch", git = "https://github.com/fluencelabs/rust-sdk"}
rusqlite = "0.25.1"
