version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  Build and test Rust service:
    docker:
      - image: circleci/rust:latest
    resource_class: xlarge
    environment:
      RUST_BACKTRACE: full
    steps:
      - checkout
      - run: |
          sudo bash .github/download_marine.sh
      - restore_cache:
          keys:
            - aqua-dht05-{{ checksum "service/Cargo.lock" }}
      - run: |
          cd ./service
          rustup target add wasm32-wasi
      - run: ./service/build.sh
      - run: |
          cd ./service
          cargo test --no-fail-fast --release --all-features -- --test-threads=1
      - save_cache:
          paths:
            - ~/.cargo
            - ~/.rustup
          key: aqua-dht05-{{ checksum "service/Cargo.lock" }}

workflows:
  version: 2
  CircleCI:
    jobs:
      - Build and test Rust service
