version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  Build and test Rust service:
    docker:
      - image: cimg/rust:1.53
    resource_class: xlarge
    environment:
      RUST_BACKTRACE: full
    working_directory: ~/project/service
    steps:
      - checkout:
          path: ~/project
      - run: |
          sudo bash .github/download_marine.sh
      - restore_cache:
          keys:
            - aqua-dht05-{{ checksum "service/Cargo.lock" }}
      - run: |
          rustup toolchain install nightly-2021-04-24-x86_64-unknown-linux-gnu
          rustup default nightly-2021-04-24-x86_64-unknown-linux-gnu
          rustup override set nightly-2021-04-24-x86_64-unknown-linux-gnu
      - run: ./build.sh
      - run: |
          cargo test --no-fail-fast --release --all-features -- --test-threads=1
      - save_cache:
          paths:
            - ~/.cargo
            - ~/.rustup
          key: aqua-dht05-{{ checksum "service/Cargo.lock" }}

workflows:
  version: 2
  CircleCI:
    jobs:
      - Build and test Rust service
