# yaml-language-server: $schema=schemas/docker-compose.json

# Defines a multi-containers based application.

# Documentation: https://github.com/fluencelabs/cli/tree/main/docs/configs/docker-compose.md

version: "3"

services:
  chain:
    image: fluencelabs/chain-rpc:0.2.20
    ports:
      - 8545:8545
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 5001:5001
      - 4001:4001
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./ipfs/:/container-init.d/
  nox-0:
    image: fluencelabs/nox:0.16.3
    pull_policy: always
    ports:
      - 7771:7771
      - 9991:9991
    environment:
      WASM_LOG: info
      RUST_LOG: debug,particle_reap=debug,aquamarine=warn,aquamarine::particle_functions=debug,aquamarine::log=debug,aquamarine::aqua_runtime=error,ipfs_effector=off,ipfs_pure=off,system_services=debug,marine_core::module::marine_module=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,cranelift_codegen=info,wasmer_wasi=info,run-console=trace,wasmtime_cranelift=off,wasmtime_jit=off,libp2p_tcp=off,libp2p_swarm=off,particle_protocol::libp2p_protocol::upgrade=info,libp2p_mplex=off,particle_reap=off,netlink_proto=warn
      FLUENCE_MAX_SPELL_PARTICLE_TTL: 9s
      FLUENCE_ROOT_KEY_PAIR__PATH: /run/secrets/nox-0
    command:
      - --config=/run/configs/nox-0_Config.toml
      - --external-maddrs
      - /dns4/nox-0/tcp/7771
      - /dns4/nox-0/tcp/9991/ws
      - --allow-private-ips
      - --local
    depends_on:
      - ipfs
    volumes:
      - ./configs/nox-0_Config.toml:/run/configs/nox-0_Config.toml
    secrets:
      - nox-0
  nox-1:
    image: fluencelabs/nox:0.16.3
    pull_policy: always
    ports:
      - 7772:7772
      - 9992:9992
    environment:
      WASM_LOG: info
      RUST_LOG: debug,particle_reap=debug,aquamarine=warn,aquamarine::particle_functions=debug,aquamarine::log=debug,aquamarine::aqua_runtime=error,ipfs_effector=off,ipfs_pure=off,system_services=debug,marine_core::module::marine_module=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,cranelift_codegen=info,wasmer_wasi=info,run-console=trace,wasmtime_cranelift=off,wasmtime_jit=off,libp2p_tcp=off,libp2p_swarm=off,particle_protocol::libp2p_protocol::upgrade=info,libp2p_mplex=off,particle_reap=off,netlink_proto=warn
      FLUENCE_MAX_SPELL_PARTICLE_TTL: 9s
      FLUENCE_ROOT_KEY_PAIR__PATH: /run/secrets/nox-1
    command:
      - --config=/run/configs/nox-1_Config.toml
      - --external-maddrs
      - /dns4/nox-1/tcp/7772
      - /dns4/nox-1/tcp/9992/ws
      - --allow-private-ips
      - --bootstraps=/dns/nox-0/tcp/7771
    depends_on:
      - ipfs
    volumes:
      - ./configs/nox-1_Config.toml:/run/configs/nox-1_Config.toml
    secrets:
      - nox-1
  nox-2:
    image: fluencelabs/nox:0.16.3
    pull_policy: always
    ports:
      - 7773:7773
      - 9993:9993
    environment:
      WASM_LOG: info
      RUST_LOG: debug,particle_reap=debug,aquamarine=warn,aquamarine::particle_functions=debug,aquamarine::log=debug,aquamarine::aqua_runtime=error,ipfs_effector=off,ipfs_pure=off,system_services=debug,marine_core::module::marine_module=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,cranelift_codegen=info,wasmer_wasi=info,run-console=trace,wasmtime_cranelift=off,wasmtime_jit=off,libp2p_tcp=off,libp2p_swarm=off,particle_protocol::libp2p_protocol::upgrade=info,libp2p_mplex=off,particle_reap=off,netlink_proto=warn
      FLUENCE_MAX_SPELL_PARTICLE_TTL: 9s
      FLUENCE_ROOT_KEY_PAIR__PATH: /run/secrets/nox-2
    command:
      - --config=/run/configs/nox-2_Config.toml
      - --external-maddrs
      - /dns4/nox-2/tcp/7773
      - /dns4/nox-2/tcp/9993/ws
      - --allow-private-ips
      - --bootstraps=/dns/nox-0/tcp/7771
    depends_on:
      - ipfs
    volumes:
      - ./configs/nox-2_Config.toml:/run/configs/nox-2_Config.toml
    secrets:
      - nox-2

secrets:
  nox-0:
    file: secrets/nox-0.txt
  nox-1:
    file: secrets/nox-1.txt
  nox-2:
    file: secrets/nox-2.txt
