[package]
name = "registry"
version = "0.8.1"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[[bin]]
name = "registry"
path = "src/main.rs"

[dependencies]
bs58 = "0.4.0"
marine-rs-sdk = "0.7.1"
marine-sqlite-connector = "0.6.0"
fstrings = "0.2.3"
boolinator = "2.4.0"
toml = "0.5.10"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
sha2 = "0.10.6"
fluence-keypair = "0.8.1"
libp2p-core = { version = "0.36.0", default-features = false, features = [ "secp256k1" ] }

[dev-dependencies]
marine-rs-sdk-test = "0.8.1"
rusqlite = "0.28.0"

[build-dependencies]
marine-rs-sdk-test = "0.8.1"
