name: "registry"

on:
  pull_request:
  push:
    branches:
      - "master"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  service:
    name: "Build and test Rust service"
    runs-on: builder

    env:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always

    defaults:
      run:
        working-directory: service

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-wasi
          default: true
          components: rustfmt, clippy

      - name: "Install libsqlite"
        run: apt-get install libsqlite3-dev

      - name: "Cache rust"
        uses: Swatinem/rust-cache@v1

      - name: "Download marine"
        run: $GITHUB_WORKSPACE/.github/download_marine.sh

      - name: "cargo fmt"
        run: cargo fmt --all -- --check

      - name: "Build Aqua DHT service"
        run: ./build.sh

      - name: "cargo check"
        run: cargo check -v --all-features

      - name: "cargo test"
        run: cargo test run --release --all-features --no-fail-fast

      - name: "cargo clippy"
        run: cargo clippy -Z unstable-options --all

  example:
    name: "Test example"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: example

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Install example dependencies"
        uses: bahmutov/npm-install@v1
        with:
          working-directory: example

      - name: "Run example"
        run: npm run start
