[package]
name = "registry-distro"
version = "0.8.4"
edition = "2021"
build = "built.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
maplit = "1.0.2"

[build-dependencies]
built = "0.5.2"
